### ISSUE TITLE
Add support for password protected zip

### ISSUE THREAD

**Issue by olamotte** [lewpaw/mansparse#1]
Traceback (most recent call last):
  File "mansparse.py", line 157, in <module>
    unzip_mans()
  File "mansparse.py", line 57, in unzip_mans
    zip_ref.extractall(workdir)
  File "c:\Python34_64\lib\zipfile.py", line 1240, in extractall
    self.extract(zipinfo, path, pwd)
  File "c:\Python34_64\lib\zipfile.py", line 1228, in extract
    return self._extract_member(member, path, pwd)
  File "c:\Python34_64\lib\zipfile.py", line 1290, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "c:\Python34_64\lib\zipfile.py", line 1190, in open
    "required for extraction" % name)
RuntimeError: File <zipfile.ZipInfo object at 0x0000000002C42708> is encrypted, password required for extraction

**Comment by olamotte** [comment]
See fix below to handle this exception:

def unzip_mans():
	if not args.silent:
		print("[OK] Unzipping file "+args.source+ " to "+workdir)
		print("[INFO] This may take a while")
	zip_ref = zipfile.ZipFile(args.source, 'r')
	try: 
		zip_ref.extractall(workdir)
	except RuntimeError as e: 
		print("[INFO] Zip seems password protected")
		zip_pass = input("Enter zip password")
		try: 
			zip_ref.extractall(workdir, pwd=bytes(zip_pass, 'utf-8') )
		except Exception as default_error:
			raise default_error
	finally:
		zip_ref.close()
